// Auto-generated by T4
namespace IntegrationTest.Generated
{
    public static class GeneratedConstants
    {
        public const string Message = "Hello from T4!";
        public const int Answer = 42;
        public static readonly string[] Items = new[] {
            "Item 1",
            "Item 2",
            "Item 3",
            "Item 4",
            "Item 5",
        };
    }
}
